FROM apache/airflow:3.3.1-python3.11

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY --chown=airflow:root 09_dag.py /opt/airflow/dags/09_dag.py
COPY --chown=airflow:root 02_generate_synthetic_data.py 04_validate_data.py 05_transform_data.py 06_load_postgres.py 08_load_doris.py 07_record_dbt_test_results.py /opt/project/
COPY --chown=airflow:root dbt_project /opt/project/dbt_project
