FROM apache/airflow:3.3.1-python3.11

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY --chown=airflow:root dag.py /opt/airflow/dags/dag.py
COPY --chown=airflow:root generate_synthetic_data.py validate_data.py transform_data.py load_postgres.py load_doris.py record_dbt_test_results.py /opt/project/
COPY --chown=airflow:root dbt_project /opt/project/dbt_project
