name: "zomato_analytics"
version: "1.0.0"
config-version: 2

profile: "zomato_analytics"

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  zomato_analytics:
    +materialized: table
