version: 2

models:
  - name: dim_restaurant
    columns:
      - name: restaurant_id
        data_tests: [not_null, unique]
      - name: location_id
        data_tests:
          - relationships:
              to: ref('dim_location')
              field: location_id

  - name: dim_location
    columns:
      - name: location_id
        data_tests: [not_null, unique]

  - name: dim_cuisine
    columns:
      - name: cuisine_id
        data_tests: [not_null, unique]

  - name: bridge_restaurant_cuisine
    columns:
      - name: restaurant_id
        data_tests:
          - relationships:
              to: ref('dim_restaurant')
              field: restaurant_id
      - name: cuisine_id
        data_tests:
          - relationships:
              to: ref('dim_cuisine')
              field: cuisine_id

  - name: dim_customer
    columns:
      - name: customer_id
        data_tests: [not_null, unique]

  - name: dim_delivery_partner
    columns:
      - name: delivery_partner_id
        data_tests: [not_null, unique]

  - name: dim_date
    columns:
      - name: date_id
        data_tests: [not_null, unique]

  - name: dim_time
    columns:
      - name: hour_id
        data_tests: [not_null, unique]

  - name: fact_orders
    columns:
      - name: order_id
        data_tests: [not_null, unique]
      - name: customer_id
        data_tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: restaurant_id
        data_tests:
          - relationships:
              to: ref('dim_restaurant')
              field: restaurant_id

  - name: fact_order_items
    columns:
      - name: order_item_id
        data_tests: [not_null, unique]
      - name: order_id
        data_tests:
          - relationships:
              to: ref('fact_orders')
              field: order_id

  - name: fact_deliveries
    columns:
      - name: delivery_id
        data_tests: [not_null, unique]
      - name: order_id
        data_tests:
          - relationships:
              to: ref('fact_orders')
              field: order_id

  - name: fact_payments
    columns:
      - name: payment_id
        data_tests: [not_null, unique]
      - name: order_id
        data_tests:
          - relationships:
              to: ref('fact_orders')
              field: order_id

  - name: fact_reviews
    columns:
      - name: review_id
        data_tests: [not_null, unique]
      - name: restaurant_id
        data_tests:
          - relationships:
              to: ref('dim_restaurant')
              field: restaurant_id
